### ISSUE TITLE
use etcd to replace lookupd?

### ISSUE THREAD

**Issue by dingoxiong** [bitly/nsq#580]
For service discover, etcd is good,  

can we use etcd to replace nsq lookupd?

Or has any plan to add a adapter for etcd?

**Comment by stephensearles** [comment]
The current plan is to use "[gossip](https://www.serfdom.io/)". The remaining requirement is that all nodes must be seeded with at least one peer's address in order to join the cluster. I don't think etcd will be as efficient or robust as to make sense replacing gossip altogether, but I could imagine it being useful in distributing a seed address in a large deployment. I'm just not sure what that integration would look like and it may be that the integration would be better suited near the process management layer (e.g. supervisord).

If you want to try out gossip, build nsq from the [dev branch](https://github.com/bitly/nsq/tree/dev).

**Comment by mreiferson** [comment]
@stephensearles agreed - ideally the distribution of your seed list is an exercise left to the user.

Going to close this, thanks for chiming in!

**Comment by dingoxiong** [comment]
Thanks, i will take a look at gossip.
