### ISSUE TITLE
nsqd: why does the diskbuffer not use a bufio writer?

### ISSUE THREAD

**Issue by Dieterbe** [bitly/nsq#621]
asking because i noticed the included benchmarks test straight writing vs buffered writing, and buffered writing comes out as much faster (at least on my system, with SSD):

```
BenchmarkDiskWrite	 3000000	       516 ns/op	 495.39 MB/s
BenchmarkDiskWriteBuffered	20000000	        91.2 ns/op	2806.79 MB/s
```
yet, the diskbuffer uses straight writes?

**Comment by mreiferson** [comment]
Because it's a queue, it needs to be able to (potentially) immediately coordinate across reads and writes.  If we buffered writes in memory we would also need to write a custom buffering implementation that is also able to be read from seamlessly, which is arguably exactly what the "in memory" queue already provides.
