### ISSUE TITLE
nsqadmin some fields unclear

### ISSUE THREAD

**Issue by Dieterbe** [bitly/nsq#629]
1. some of the fields are current state (depth, in-mem, on disk) which reset to 0 in good circumstances, while others don't reset and seem to be totals from start until now. like messages, and i think requeued/timed out as well? (i have timed out = 1 for more than hour, so i presume/hope that message has been processed just fine since then ?) 

2. some fields include each other.  I hear Requeued includes "Timed out" for example, but not "Deferred". this is confusing.

**Comment by jehiah** [comment]
It's a fair comment that these could be documented better. We've tried to keep the nsqadmin ui compact and have avoided paragraphs of definitions there.

In nsqadmin, the counters for message state where numbers represent actual messages are labeled as 'Message Queues'. The ones that are lifetime statistics since node or connection startup are labeled 'Statistics'.

### Message Queues:

* Depth: sum(message in memory + messages on disk). This is the count a client can consume immediately
* In-Flight: a message sent to a client but not yet REQ or FIN'd or Timed out
* Deferred: Messages that were REQ'd or Timed out and are not yet available for delivery to a client

### Statistics:

* Requeued: messages delivered to a client and subsequently moved to the deferred queue for later retry
* Timed Out: messages delivered to a client that didn't receive a response before configured timeout that were server-side requeued.
* Messages: total count of new messages

### Client Connections: 

* In-flight: the number of messages sent to that connection not yet FIN or REQ'd
* Ready Count: the max number of messages that can be in-flight on this connection
* Finished: sum(FIN) responses
* Requeued: sum(REQ) responses
* Messages: count() messages sent 

Also for context for anyone else that comes across this thread, here is an appropriate nsqadmin screenshot.

![screen shot 2015-08-14 at 9 29 30 am](https://cloud.githubusercontent.com/assets/45028/9275012/3378f0cc-4268-11e5-904b-a1af9eb401b3.png)

**Comment by Dieterbe** [comment]
thanks a lot jehiah.
